# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.11.0


## Tensor (n-dimensional array)

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world
result      #Operation doesn't happen outside the session

<tf.Tensor 'add:0' shape=() dtype=string>

In [7]:
type(result)

tensorflow.python.framework.ops.Tensor

In [8]:
# Operation happens only inside a session
with tf.Session() as sess:
    result = sess.run(hello + world)

result     #b represents byte literal

b'HelloWorld'

### Computation

In [9]:
tensor_1 = tf.constant(10)
tensor_2 = tf.constant(20)

In [10]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [11]:
type(tensor_2)

tensorflow.python.framework.ops.Tensor

In [12]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(tensor_1 + tensor_2)

result

30

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)    #4*4 matrix filled with 10 all values   

In [18]:
myzeros = tf.zeros((4,4))   #4*4 matrix filled with 0 all values

In [19]:
myones = tf.ones((4,4))   #4*4 matrix filled with 1 all values

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)   #4*4 matrix filled with random values from normal distribution

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)  #4*4 matrix filled with random values from uniform distribution

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]   #List of all above operations

## Interactive Session
Useful for Notebook Sessions

In [23]:
# Only run this cell once!
#Interactive Session will be valid on other cells of a notebook ie. outside the session.
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(sess.run(op))  #or print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.23189583 -0.59747946  0.23092192  0.11139537]
 [ 0.2757412  -0.04704673 -0.41825458  0.8461513 ]
 [-0.7250557   0.01817349  0.22711791  0.46513265]
 [-0.03143486  1.0284894  -0.07658974 -0.6139658 ]]


[[0.73695064 0.32957983 0.882009   0.10286295]
 [0.3679465  0.13795769 0.51513875 0.03603554]
 [0.39505124 0.32872975 0.14966524 0.13893998]
 [0.97630477 0.7416563  0.6450926  0.28771174]]




## Matrix Multiplication

In [25]:
a = tf.constant([ [1,2],
                  [3,4],
                  [5,6]])

In [26]:
a.get_shape()

TensorShape([Dimension(3), Dimension(2)])

In [27]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [29]:
result = tf.matmul(a,b)

In [33]:
result.eval()


array([[210],
       [430],
       [650]])

In [35]:
sess.run(result)

array([[210],
       [430],
       [650]])